### ISSUE TITLE
Running the thebe interactive Command, octave produces a weird qt error

### ISSUE THREAD

**Issue by joergbrech** [hbrs-cse/Modellbildung-und-Simulation#242]
![grafik](https://user-images.githubusercontent.com/25240961/152201752-8d8622a0-eb48-42ad-8c7a-43a21bc7cd6f.png)

It dissapears after clicking Run again.

**Comment by joergbrech** [comment]
Could maybe be fixed with some magic octave command in https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/.binder/postBuild, but who knows 😝

**Comment by PhiSpel** [comment]
Change something in Modellbildung-und-Simulation)/.binder/

The clue is somewhere here https://mybinder.readthedocs.io/en/latest/

**Comment by PhiSpel** [comment]
Running `available_graphics_toolkits ()` returns 

`ans = 
{
  [1,1] = gnuplot
}`

The qt-error can be reproduced permanently when adding `graphics_toolkit("qt");` to the first line. Octave seems to be smart enough, though, to choose a different toolkit instead.

When verifying my local installation as seen [here](https://abdallahshamy.wordpress.com/2021/06/24/gsoc-2021-how-to-setup-the-octave-kernel-for-jupyter/), it turns out my installation has no default toolkit.

qt appears to be the most advanced graphics toolkit, so I will try and find out how to install it when installing the octave_kernel using binder

**Comment by PhiSpel** [comment]
I tried this again, today, and could not reproduce the error!

@Florian314 @VictorLued @LeaKruehler @rstrickstrock 
Could you try to reproduce the error?:
- Open the [starting page](https://hbrs-cse.github.io/Modellbildung-und-Simulation/intro.html)
- Start the "Live Code" function (under the rocket on the top right of page)
- wait for mybinder to start the kernel
- execute the codebox (remove "Copy to clipboard" in the last line)
Do you see only the image, or also this error?
![grafik](https://user-images.githubusercontent.com/25240961/152201752-8d8622a0-eb48-42ad-8c7a-43a21bc7cd6f.png)

**Comment by PhiSpel** [comment]
I checked it again - seems to be working now! :)
