### ISSUE TITLE
get new DOI

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#410]
- [x] #411
- [x] reinclude dois
- [x] #452
- [x] update the zenodo DOIs

**Comment by PhiSpel** [comment]
We got a response. Apparently, HBRS cannot give out their own DOIs, so we should stick to the zenodo one - or to one we may get from ORCA?
@joergbrech, let's discuss this in the next JF

**Comment by joergbrech** [comment]
Personally, I don't mind the zenodo DOI that much. I like how we can automate the DOI creation with git tags.

**Comment by PhiSpel** [comment]
Then, I'll bump the zenodo version to 1.0, as this is also the version in the citation file. For the ORCA repository, we may get a new doi, but this will be another issue

**Comment by PhiSpel** [comment]
@joergbrech, I drafted a release for the v1.0.0-alpha. Do you agree with the draft?

**Comment by joergbrech** [comment]
Let's make sure, that the Zenodo DOI, the git tag and the citation file version are always consistent. If my understanding is correct, Zenodo will parse the citation file and create a new DOI with every git tag *(I just re-enabled ZENODO integration for this repo. This was lost when we moved from my account to hbrs-cse)*.

I suggest writing down a release guide *(either in the wiki or a markdown file)* to make sure that citation file, DOI and git tag are consistent: 

 - Bump the version in the citation file (e.g. we would need to explicitly write `v1.0.0-alpha`)
 - Create a Git Tag with the exact same version string as in the citation file.
 - Navigate to Zenodo, make sure that a new DOI was properly created
 - Update the DOI in README.md and the citation file

One additional suggestion let's call the draft `v1.0.0-alpha0`, so that we are prepared to create several alpha releases until this all works out the way we want it to? 😝

**Comment by PhiSpel** [comment]
Okay, will do :)

**Comment by PhiSpel** [comment]
@joergbrech the new release does not show up on zenodo. Does this just take some time or did the zenodo integration fail somewhere?

Also, I added the .zenodo.json file again for citation via zenodo.

**Comment by joergbrech** [comment]
I can see the error when I login to zenodo:

```
{
    "errors": "The license ID you have selected is not present in our system. For the available licenses please check in the following URL https://developers.zenodo.org/#licenses"
}
```

So I think we need to change this line:

https://github.com/hbrs-cse/Modellbildung-und-Simulation/blob/cca2c6c07d89162b2a03f369243705da262ae162/CITATION.cff#L48 

to 

```yaml
license: cc-by-nc-sa-4.0
```

Zenodo seems to be using the license ids from https://spdx.org/licenses/.

**Comment by joergbrech** [comment]
Also: We do not need the `zenodo.json` anymore. Zenodo should be able to parse the `CITATION.cff` file. Otherwise we would have to maintain both files

**Comment by joergbrech** [comment]
Now let's delete the failed tag and create it again with the corrected `CITATION.cff`.

**Comment by PhiSpel** [comment]
Hmm, this does not seem to work, also with a new tag set to the latest master version..

**Comment by PhiSpel** [comment]
![image](https://user-images.githubusercontent.com/62760840/203107678-670b5f9c-321b-45b5-97de-f5e3ceab2409.png)

looks like something's still up

**Comment by joergbrech** [comment]
💩 I see the same error message as before. But what is strange is that it seems to pick up the `alpha0` tag. Maybe zenodo tries to pick up the latest release, but cannot handle the pre-release identifier `-alphaX`?

**Comment by PhiSpel** [comment]
> Do you think deleting the two tags and then creating a new `alpha0` tag is worth a shot?

It was! 😄  I also changed to `alpha.0`, I supposed this may make a difference, as I saw it in some example for pre-releases

**Comment by joergbrech** [comment]
> > Do you think deleting the two tags and then creating a new `alpha0` tag is worth a shot?
> 
> It was! 😄  I also changed to `alpha.0`, I supposed this may make a difference, as I saw it in some example for pre-releases

According to [Semver](https://semver.org/) it shouldn't, but who knows? :shrug:
