### ISSUE TITLE
Consider adding git exercises

### ISSUE THREAD

**Issue by joergbrech** [hbrs-cse/Modellbildung-und-Simulation#415]
I used these two templates as part of my lecture 2020 in github classroom:
https://github.com/joergbrech/modsim2-projektbeschreibung
https://github.com/joergbrech/modsim2-ausarbeitung

**Comment by PhiSpel** [comment]
I think we should add the [GitHub minimal example](https://github.com/joergbrech/modsim2-projektbeschreibung) as an exercise. I will clone it and adapt it, so that @joergbrech will not always be assigned the issue :)

I do not think that we should include the [LaTeX project](https://github.com/joergbrech/modsim2-ausarbeitung) in the website, as the code cannot be run online - unless you use, say, Overleaf, which already has many good templates and works nearly as well as a WYSIWYG editor. However, it can and should be used as a reference in the ModSim lecture, if we want to introduce git, see #468.

**Comment by PhiSpel** [comment]
See [here](https://github.com/hbrs-cse/github-project-template)

For now, I simply removed the parts concerning the ModSim Ausarbeitung. I think, we can add this as a chapter online. I will address this in our first meeting in 2023
