### ISSUE TITLE
Test mirroring

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#437]
before mirroring into the orca nrw repo

**Comment by joergbrech** [comment]
We only need a copy of the `master` branch, right?

**Comment by PhiSpel** [comment]
Right

**Comment by PhiSpel** [comment]
Oh, and `gh-pages` would be good, I think

**Comment by joergbrech** [comment]
I think I might have a working setup here: https://github.com/joergbrech/Modellbildung-und-Simulation

 - I created a mirror using https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository#mirroring-a-repository-in-another-location and `git push`ed the master 
 - I pushed the `master` and `gh-pages` branches
 - I created a new scheduled workflow on the `master` branch that uses https://github.com/aormsby/Fork-Sync-With-Upstream-action, see https://github.com/joergbrech/Modellbildung-und-Simulation/commit/2da8dc3a8c0695631c91fc9c4e4dbb37eeae3893

It remains to see if the syncronization works after we have make some changes to the two branches here. 

The fact that the mirror is public and is in the old location of our repo has the added benefit, that the QR codes in the old exercise sheets should now work again, because the site is hosted under the old location as well.

**Comment by PhiSpel** [comment]
Thank you very much for your contribution! Are you confident, that this routine works in a private repo as well?

Let's see what happens now that I merged #448

**Comment by joergbrech** [comment]
Looks good: https://github.com/joergbrech/Modellbildung-und-Simulation *(I just triggered the workflow manually)*

Yes I am relatively confident it should work *from* a private mirror, since it pulls from a public repo.

**Comment by PhiSpel** [comment]
Wonderful! Then, we are well prepared for when we get our ORCA repo :)

**Comment by joergbrech** [comment]
One more remark: We could consider forking my repo at ORCA:
 - Setup would be as easy as pushing a button
 - It would copy the newly added workflow file for syncronizing with upstream which should work out of the box
 - The repo under my username would stay intact, together with its gh-pages, so that the QR-codes in older exercise sheets don't 404

That being said, a fork would probably have been the easiest option right from the start. I made it more complicated than necessary because I was thinking of Gitlab mirrors: https://docs.gitlab.com/ee/user/project/repository/mirror/. Forks don't auto-update, so we still need the additional workflow file.

**Comment by PhiSpel** [comment]
> I made it more complicated than necessary

As you said, the fork would not auto-update, so I think your solution makes a lot of sense!

Setting up the ORCA repo as a fork of your repo could make sense, but leave you responsible of keeping your GitHub intact, so a copy may be better (?)

**Comment by joergbrech** [comment]
> Also, do I understand correctly, that the gitlab feature simply isn't available on GitHub?

I think so...

> Setting up the ORCA repo as a fork of your repo could make sense, but leave you responsible of keeping your GitHub intact, so a copy may be better (?)

I think forks can outlive the upstream repo, they should be fairly independent after the fork. But I am fine either way, forking is just easier because there is a button for it 😛
