### ISSUE TITLE
Make sure Leas changes were kept

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#441]
In PR #192 some changes by @LeaKruehler seem to have been reverted. For example, 

https://github.com/hbrs-cse/Modellbildung-und-Simulation/blob/a58cabb2e0b0f226122fcc10c08f6754d39aa09e/content/00_einleitung/01_motivation.ipynb?short_path=0b12a8d#L38

Go through #192 and revert, what's necessary.

**Comment by LeaKruehler** [comment]
I'm concerned that other changes you've made have also been reverted.

For example this one: 
![#441](https://user-images.githubusercontent.com/91247914/200268242-e72c3214-9eb5-477c-ad60-49451f007b45.PNG)

**Comment by LeaKruehler** [comment]
I reverted everything that was originally changed by me. 
I made the changes in the #438.

**Comment by PhiSpel** [comment]
> I'm concerned that other changes you've made have also been reverted.
> 
> For example this one: ![#441](https://user-images.githubusercontent.com/91247914/200268242-e72c3214-9eb5-477c-ad60-49451f007b45.PNG)

This change does not come up anymore in #438, did you correct it?

**Comment by LeaKruehler** [comment]
No I haven't changed it.
In #438 is the older version (the green one here, which was once changed to the red version) and I suspect it didn't show up as a change because it wasn't changed.
I think it's best way if you check all other changes in #192 (except spelling) and check in #438 if it's the right version or needs to be changed. What do you think?

**Comment by PhiSpel** [comment]
I went through the changes as analysed in #438, they seem to be fine

**Comment by LeaKruehler** [comment]
Okay, then we have to be careful with merging #192, right?

**Comment by PhiSpel** [comment]
#192 is already merged, so no worries there

**Comment by LeaKruehler** [comment]
So, just for my understanding. 
When #192 has already been merged, then the changes that are marked in #192 are not marked in #438 because they are not new and therefore not changes. 
The spelling errors that were marked as changes in #192 were not marked in #438. They are marked now because I changed them back. 

So, in my mind the changes that are marked in #192 and might not be correct have already been merged and have to be compared with the current version (like #438). 
Do you know, what I mean? Do I have a knot in my brain?

**Comment by PhiSpel** [comment]
> So, just for my understanding. When #192 has already been merged, then the changes that are marked in #192 are not marked in #438 because they are not new and therefore not changes. The spelling errors that were marked as changes in #192 were not marked in #438. They are marked now because I changed them back.

Yes. #438 compares your branch to the master, which already includes the changes from #192.
 
> So, in my mind the changes that are marked in #192 and might not be correct have already been merged and have to be compared with the current version (like #438). Do you know, what I mean? Do I have a knot in my brain?

Do you mean we still need to check the changes in #192? I do not think so. If #438 includes your changes, which were not currently on the master branch, then #438 is enough. If this does not solve it, just send me a DM :)
